# Install Jenkins
---
  - name: apt update
    apt:
      update_cache: true

  - name: Upgrade all packages
    apt:
      upgrade: dist

  - name: Install prerequisites
    apt:
      name:
        - fontconfig
        - openjdk-21-jre
        - curl
        - gnupg
      state: present

  - name: add the jenkins key
    get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /tmp/jenkins.io.key

  - name: Dearmor Jenkins GPG key   #due to GPG key is starting "-----BEGIN PGP PUBLIC KEY BLOCK-----
    ansible.builtin.shell: gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.asc /tmp/jenkins.io.key
    args:
      creates: /usr/share/keyrings/jenkins-keyring.asc

  - name: Add Jenkins apt repository
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
      state: present
      filename: jenkins

  - name: Update apt cache after adding repo
    apt:
      update_cache: true

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present

  - name: Start and enable Jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started