---
  - name: Install unzip (needed for terraform binary)
    apt:
      name: unzip
      state: present

  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.11.0/terraform_1.15.8_linux_amd64.zip
      dest: /tmp/terraform.zip

  - name: Unzip Terraform
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin
      remote_src: true
      mode: '0755'

  - name: Install AWS CLI
    apt:
      name: awscli
      state: present