---
  - name: Install unzip (needed for terraform binary)
    apt:
      name: unzip
      state: present

  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip
      dest: /tmp/terraform.zip
      force:  true

  - name: Unzip Terraform
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin
      remote_src: true
      mode: '0755'

  - name: Install/upgrade AWS CLI v2
    shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      sudo ./aws/install --update
    args:
      chdir: /tmp
      
  - name: Add Kubernetes repository key
    apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
      state: present

  - name: Add Kubernetes repository
    apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
      state: present
      filename: kubernetes.list

  - name: Install kubectl via apt
    apt:
      name: kubectl
      state: present
      update_cache: yes

  - name: Allow passwordless sudo for jenkins agent user
    lineinfile:
      path: /etc/sudoers.d/jenkins-agent
      line: "jenkins ALL=(ALL) NOPASSWD:ALL"
      create: yes
      validate: 'visudo -cf %s'
      mode: '0440'