pipeline {
    agent { label 'infra-agent' }

    stages {
        stage('Checkout Git repo') {
            steps {
                checkout scmGit(
                    branches: [[name: '*']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Ostry7/aws-platform-eks-jenkins-ansible'
                    ]]
)
            }
        }

        stage('Terraform init') {
            steps {
                dir('terraform-infra'){
                    sh 'terraform fmt'
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform apply') {
            steps {
                dir('terraform-infra'){
                    sh 'terraform apply --auto-approve'
                }
            }
        }
    }
}
