pipeline {
    agent { label 'infra-agent' }

    stages {
        stage('Checkout Git repo') {
            steps {
                checkout scmGit(
                    branches: [[name: '*']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Ostry7/aws-platform-eks-jenkins-ansible'
                    ]]
)
            }
        }

        stage('Terraform init') {
            steps {
                dir('terraform-infra'){
                    sh 'terraform fmt'
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform apply') {
            steps {
                dir('terraform-infra'){
                    script {
                        env.ECR_REGION = sh(script: 'terraform output -raw ecr_region', returnStdout: true).trim()
                        env.EKS_CLUSTER_NAME = sh(script: 'terraform output -raw ecr_cluster_name', returnStdout: true).trim()
                    }
                    sh 'aws eks update-kubeconfig --region $ECR_REGION --name $EKS_CLUSTER_NAME'
                    sh 'terraform apply --auto-approve'
                }
            }
        }
    }
}
