---
  - name: Install Docker prerequisites
    apt:
      name:
        - ca-certificates
        - curl
      state: present

  - name: Install unzip (needed for terraform binary)
    apt:
      name: unzip
      state: present

  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip
      dest: /tmp/terraform.zip
      force:  true

  - name: Unzip Terraform
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin
      remote_src: true
      mode: '0755'

  - name: Install AWS CLI
    apt:
      name: awscli
      state: present

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Add jenkins user to docker group
    ansible.builtin.user:
      name: jenkins
      groups: docker
      append: true

  - name: Install python
    apt: name="python3" state=present
    become: true

  - name: Ensure docker daemon starts on boot (systemd-managed)
    ansible.builtin.systemd:
      name: docker
      enabled: true
      state: started

  - name: Download kubectl
    get_url:
      url: "https://dl.k8s.io/v1.35.5/bin/linux/amd64/kubectl"
      dest: /usr/local/bin/kubectl
      mode: '0755'

  - name: Install gettext-base (envsubst)
    apt:
      name: gettext-base
      state: present