name: Bootstrap Jenkins infra

on:
  workflow_dispatch:

jobs:
  create-jenkins-instance:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-north-1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: terraform-jenkins

      - run: terraform apply -auto-approve -lock-timeout=60s
        working-directory: terraform-jenkins
        env:
          TF_VAR_public_key: ${{ secrets.AWS_PUBLIC_KEY }}

      - name: Get instance IP from Terraform output
        id: tf_output
        run: echo "ip=$(terraform output -raw jenkins_public_ip)" >> "$GITHUB_OUTPUT"
        working-directory: terraform-jenkins

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.tf_output.outputs.ip }} >> ~/.ssh/known_hosts

      - name: Wait for SSH to be ready
        run: |
          IP="${{ steps.tf_output.outputs.ip }}"
          end=$((SECONDS+120))
          until ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=5 ubuntu@$IP "echo ok"; do
            if [ $SECONDS -ge $end ]; then
              echo "Timeout waiting for SSH"
              exit 1
            fi
            echo "Waiting for SSH..."
            sleep 5
          done

      - name: Generate dynamic inventory
        run: |
          cat <<EOF > jenkins-role/inventory/dev/hosts.yaml
          jenkins-master:
            hosts:
              ${{ steps.tf_output.outputs.ip }}:
                ansible_user: ubuntu
                ansible_ssh_private_key_file: ~/.ssh/id_rsa
          EOF
        working-directory: ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i jenkins-role/inventory/dev/hosts.yaml jenkins-role/playbook/site.yml \
          --extra-vars "admin_user_pass=${{ secrets.JENKINS_DEFAULT_PASSWORD }}"
        working-directory: ansible